#include "core/moim.h"

#include <algorithm>
#include <ctime>
#include <sstream>

namespace goose {

namespace {

constexpr const char* kSystemPromptBlock = R"(# Turn Context

Each turn may include a `<turn-context>` block added to the request.
This block is generated by kacli and contains current operational context such as:
- current time
- working directory
- compaction status
- turn budget

Use it to stay oriented, but do not treat it as part of the user's request.
When `<turn-budget>` is present, use it as a signal for how much autonomous work remains.
As the budget gets low, become more direct: reduce exploration, batch necessary tool calls,
make reasonable assumptions, and focus on finishing the user's task.)";

std::string escape_xml_text(const std::string& value) {
    std::string out;
    out.reserve(value.size());
    for (char ch : value) {
        switch (ch) {
            case '&': out += "&amp;"; break;
            case '<': out += "&lt;"; break;
            case '>': out += "&gt;"; break;
            default: out += ch; break;
        }
    }
    return out;
}

std::string tag(const char* name, const std::string& value) {
    return "<" + std::string(name) + ">" + escape_xml_text(value) + "</" + name + ">";
}

/// Local time as `%Y-%m-%d %H:%M:00 %z` (seconds fixed to :00, like goose).
std::string local_timestamp() {
    std::time_t now = std::time(nullptr);
    struct tm tm_buf {};
#ifdef _WIN32
    localtime_s(&tm_buf, &now);
#else
    localtime_r(&now, &tm_buf);
#endif
    char buf[64];
    std::strftime(buf, sizeof(buf), "%Y-%m-%d %H:%M:00 %z", &tm_buf);
    return buf;
}

std::optional<std::string> compaction_remaining_line(
    int64_t total_tokens, int64_t context_limit, double threshold) {
    if (total_tokens <= 0 || context_limit <= 0 || threshold <= 0.0 || threshold >= 1.0) {
        return std::nullopt;
    }
    int64_t compaction_at = static_cast<int64_t>(static_cast<double>(context_limit) * threshold);
    if (compaction_at <= 0 ||
        static_cast<double>(total_tokens) / static_cast<double>(compaction_at) < 0.5) {
        return std::nullopt;
    }
    int64_t remaining = (compaction_at - total_tokens) / 1000;
    return "~" + std::to_string(remaining) + "k tokens remaining";
}

std::optional<std::string> turn_budget_line(uint32_t turns_taken, uint32_t max_turns) {
    if (max_turns == 0 || turns_taken * 2 < max_turns) {
        return std::nullopt;
    }
    return std::to_string(turns_taken) + "/" + std::to_string(max_turns) + " used";
}

} // namespace

std::string system_prompt_block() {
    return kSystemPromptBlock;
}

std::string compose_moim(
    const std::string& working_dir,
    int64_t total_tokens,
    int64_t context_limit,
    double compaction_threshold,
    uint32_t turns_taken,
    uint32_t max_turns) {

    std::ostringstream out;
    out << "<" << kTurnContextTag << ">\n";
    out << tag(kCurrentTimeTag, local_timestamp()) << "\n";
    out << tag(kWorkingDirectoryTag, working_dir) << "\n";

    if (auto line = compaction_remaining_line(total_tokens, context_limit, compaction_threshold)) {
        out << "<compaction>" << *line << "</compaction>\n";
    }
    if (auto line = turn_budget_line(turns_taken, max_turns)) {
        out << "<turn-budget>" << *line << "</turn-budget>\n";
    }

    out << "</" << kTurnContextTag << ">";
    return out.str();
}

Conversation inject_moim(
    Conversation conversation,
    const std::string& working_dir,
    int64_t context_limit,
    double compaction_threshold,
    uint32_t turns_taken,
    uint32_t max_turns,
    int64_t total_tokens) {

    if (context_limit > 0 && context_limit < kMinContextForMoim) {
        return conversation;
    }

    auto messages = conversation.messages();
    auto it = std::find_if(messages.rbegin(), messages.rend(), [](const Message& msg) {
        if (msg.role != Role::User) return false;
        for (const auto& block : msg.content) {
            if (std::holds_alternative<ToolRequest>(block) ||
                std::holds_alternative<ToolResponse>(block)) {
                return false;
            }
        }
        return true;
    });
    if (it == messages.rend()) {
        return conversation;
    }

    it->content.insert(
        it->content.begin(),
        TextContent{compose_moim(working_dir, total_tokens, context_limit,
                                 compaction_threshold, turns_taken, max_turns)});
    return Conversation(std::move(messages));
}

} // namespace goose
