#!/usr/bin/env python3
"""Generate prompt_templates_generated.h from the .md templates under src/prompts."""
import sys
from pathlib import Path

SRC = Path(sys.argv[1])
OUT = Path(sys.argv[2])

DESCRIPTIONS = {
    "system.md": "Full system prompt",
    "compaction.md": "Summarization of conversation history",
    "compaction_summary.md": "Renders structured compaction output",
    "permission_judge.md": "Read-only detection for tool ops",
    "tiny_model_system.md": "System prompt for tiny local models",
}

ORDER = [
    "system.md",
    "compaction.md",
    "compaction_summary.md",
    "permission_judge.md",
    "tiny_model_system.md",
]

entries = []
for name in ORDER:
    content = (SRC / name).read_text(encoding="utf-8")
    desc = DESCRIPTIONS.get(name, name)
    entries.append((name, desc, content))

lines = []
lines.append("// auto-generated by scripts/gen_prompts.py -- do not edit")
lines.append("#pragma once")
lines.append("#include <string_view>")
lines.append("namespace goose {")
lines.append("namespace embedded {")
lines.append("struct EmbeddedTemplate {")
lines.append("    std::string_view name;")
lines.append("    std::string_view description;")
lines.append("    std::string_view content;")
lines.append("};")
lines.append("inline constexpr EmbeddedTemplate kEmbeddedTemplates[] = {")
for name, desc, content in entries:
    lines.append('    {"%s", "%s", R"KACLI_TMPL(' % (name, desc))
    lines.append(content)
    lines.append(')KACLI_TMPL"},')
lines.append("};")
lines.append("inline constexpr size_t kEmbeddedTemplateCount = %d;" % len(entries))
lines.append("} // namespace embedded")
lines.append("} // namespace goose")

OUT.parent.mkdir(parents=True, exist_ok=True)
OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
print(f"generated {OUT} with {len(entries)} templates")
